remote_theme: pmarsceill/just-the-docs
title: ''
search_enabled: true

aux_links:
  "Download Overview PDF":
    - "https://github.com/hidglobal/digitalpersona-access-management-api/blob/master/docs/assets/DigitalPersona-Access-Management-API.pdf"
  "[View Repos]":
    - "https://github.com/hidglobal/digitalpersona-access-management-api/"
  "[Link button](http://example.com/){: .btn .btn-green }"
