remote_theme: pmarsceill/just-the-docs
title: ''
search_enabled: true

aux_links:
  "[Download Overview PDF]":
    - "docs\assets\DigitalPersona Access Management API.pdf"
  "[View Repo]":
    - "https://github.com/hidglobal/digitalpersona-access-management-api/"
